off/urls.py
#!/usr/bin/python3
# -*- coding: Utf-8 -*

from django.urls import path, re_path
from django.views.generic import TemplateView

from . import views

app_name = "off"

urlpatterns = [
    path("", views.index, name="index"),
    path("resultats", views.results, name="results"),
    path("mes-produits", views.saved_products, name="saved-products"),
    re_path(r"^produit/(?P<id_product>[^/]+)$", views.product, name="product"),
    path("mon-compte", views.account, name="account"),
    path("mentions-legales", TemplateView.as_view(template_name="off/legal_notices.html"), name="legal-notices"),
    path("contact", TemplateView.as_view(template_name="off/contact.html"), name="contact"),
]

urlpatterns += [
    path("inscription", views.register, name="register"),
    path("mot-de-passe", views.change_password, name="change-password")
]

off_project/urls.py
#!/usr/bin/python3
# -*- coding: Utf-8 -*

"""off_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("off.urls", "off"), namespace="off")),
]

urlpatterns += [
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
    )

off/models.py
#!/usr/bin/python3
# -*- coding: Utf-8 -*

from django.db import models
from django.conf import settings
from django.utils.translation import gettext as _
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager

# Create your models here.


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Product(models.Model):
    off_id = models.BigIntegerField(_("id"), null=True)
    name = models.CharField(_("nom"), max_length=200, null=True)
    picture = models.URLField(_("image"), null=True)
    proteins = models.CharField(_("protéines"), max_length=200, null=True)
    salt = models.CharField(_("sel"), max_length=200, null=True)
    fat = models.CharField(_("matières grasses"), max_length=200, null=True)
    sugars = models.CharField(_("sucres"), max_length=200, null=True)
    carbohydrates = models.CharField(_("glucides"), max_length=200, null=True)
    nutriscore_grade = models.CharField(
                            _("nutriscore"),
                            max_length=2,
                            null=True
                        )
    category = models.CharField(_("catégorie"), max_length=200, null=True)
    url = models.URLField(_("fiche OpenFoodFacts"), null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name

off/forms.py
#!/usr/bin/python3
# -*- coding: Utf-8 -*

from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
)
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("email",)
        widgets = {
            "email": forms.TextInput(attrs={"class": "form-control"}),
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)


class AuthenticationFormApp(AuthenticationForm):
    def confirm_login_allowed(self, user):
        pass

off/views.py
#!/usr/bin/python3
# -*- coding: Utf-8 -*

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, update_session_auth_hash, login as auth_login
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

from .models import Product, CustomUser
from .forms import CustomUserCreationForm, AuthenticationFormApp
from .constantes import (
    NO_CHARS_LIST,
    STOP_WORDS,
)
from unidecode import unidecode

# Create your views here.


def register(request):
    ref_url = 'off:' + request.resolver_match.url_name
    if request.method == "GET":
        form = CustomUserCreationForm()

    if request.method == "POST":
        if request.POST.get("query"):
            request.session["input_user"] = request.POST.get("query")
            return redirect("off:results")
        
        else:
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data["email"]
                password = form.cleaned_data["password1"]
                password2 = form.cleaned_data["password2"]
                if password == password2:
                    form.save()
                    user = authenticate(email=email, password=password)
                    if user is not None:
                        auth_login(request, user)
                        return redirect("off:index")
                else:
                    # form = CustomUserCreationForm()
                    print("passwords not equals")
            else:
                print("Register not valid")

    return render(request, "registration/register.html", {
        "form": form,
        "ref_url": ref_url,
    })


def login(request):
    ref_url = 'off:' + request.resolver_match.url_name
    if request.user.is_authenticated:
        return redirect("off:index")

    if request.method == "GET":
        form = AuthenticationFormApp()
        return render(request, "registration/login.html", {
            "form": form,
            "ref_url": ref_url,
        })

    if request.method == "POST":
        form = AuthenticationFormApp(request=request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(email=email, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect("off:index")
        else:
            print("User not found")


def index(request):

    error_message_empty = False
    error_message_wrong = False

    if request.method == "POST":
        if request.POST.get("query"):
            request.session["input_user"] = request.POST.get("query")
            return redirect("off:results")

    return render(request, "off/index.html", {
            "error_message_empty": error_message_empty,
            "error_message_wrong": error_message_wrong,
    })


@login_required(login_url="login")
def change_password(request):
    ref_url = 'off:' + request.resolver_match.url_name
    message_validation = False

    if request.method == 'GET':
       form = PasswordChangeForm(user=request.user)

    if request.method == 'POST':
        if request.POST.get("query"):
            request.session["input_user"] = request.POST.get("query")
            return redirect("off:results")
        else:
            form = PasswordChangeForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(request, 'Votre mot de passe a bien été modifié.')   
                return redirect("off:change-password")
            else:
                print("Can't change password")

    return render(request, "registration/change_password.html", {
        "message_validation": message_validation,
        "form": form,
        "ref_url": ref_url,
    })


@login_required(login_url="login")
def results(request):
    ref_url = 'off:' + request.resolver_match.url_name
    error_message_empty = False
    error_message_no_results = False
    list_saved_id_products = []

    if request.method == "POST":
        if request.POST.get("query"):
            input_brut = request.POST.get("query")
            input_withoutCharsSpe = input_brut.translate(
                {ord(c): " " for c in NO_CHARS_LIST}
            )
            input_no_accent = unidecode(input_withoutCharsSpe)
            input_split = input_no_accent.split()

            for element in input_split:
                if element in STOP_WORDS:
                    input_split.remove(element)

            if not input_split:
                error_message_empty = True

            else:
                request.session["search"] = input_split
                request.session["input_user"] = input_brut

        # details product
        if request.POST.get("product"):
            return redirect("off:product", request.POST.get("product"))

        # save product
        if request.POST.get("save"):
            current_user = request.user
            product = get_object_or_404(Product, pk=request.POST.get("save"))
            user = get_object_or_404(CustomUser, pk=current_user.id)
            user.product_set.add(product)

            for element in user.product_set.all():
                list_saved_id_products.append(element.id)

    if request.method == "GET":

        current_user = request.user
        user = get_object_or_404(CustomUser, pk=current_user.id)

        for element in user.product_set.all():
            list_saved_id_products.append(element.id)

        input_brut = request.session["input_user"]
        input_withoutCharsSpe = input_brut.translate(
            {ord(c): " " for c in NO_CHARS_LIST}
        )
        input_no_accent = unidecode(input_withoutCharsSpe)
        input_split = input_no_accent.split()

        for element in input_split:
            if element in STOP_WORDS:
                input_split.remove(element)

        if not input_split:
            error_message_empty = True
        
        else:
            request.session["search"] = input_split
            request.session["input_user"] = input_brut
 

    categories_products = []
    for word in request.session["search"]:
        for product in Product.objects.filter(name__icontains=word):
            categories_products.append(product.category)

    if categories_products:
        main_category = max(
            set(categories_products),
            key=categories_products.count
        )
        substitute_products_list = Product.objects.filter(
            category=main_category
        ).order_by("nutriscore_grade", "name")[:12]
        paginator = Paginator(substitute_products_list, 6)
        page = request.GET.get("page")

        try:
            substitute_products = paginator.page(page)
        except PageNotAnInteger:
            substitute_products = paginator.page(1)
        except EmptyPage:
            substitute_products = paginator.page(paginator.num_pages)

    else:
        error_message_no_results = True
        substitute_products = None

    return render( request, "off/results.html", {
            "error_message_empty": error_message_empty,
            "error_message_no_results": error_message_no_results,
            "input_user": request.session["input_user"],
            "substitute_products": substitute_products,
            "list_saved_id_products": list_saved_id_products,
            "ref_url": ref_url,
    })


@login_required(login_url="login")
def saved_products(request):
    ref_url = 'off:' + request.resolver_match.url_name
    current_user = request.user
    user = get_object_or_404(CustomUser, pk=current_user.id)
    saved_products = user.product_set.all()

    if request.method == 'POST':
        if request.POST.get("query"):
            request.session["input_user"] = request.POST.get("query")
            return redirect("off:results")

    return render(request, "off/saved.html", {
            "saved_products": saved_products,
            "ref_url": ref_url,
    })


@login_required(login_url="login")
def product(request, id_product):
    ref_url = 'off:' + request.resolver_match.url_name
    list_saved_id_products = []
    current_user = request.user
    user = get_object_or_404(CustomUser, pk=current_user.id)

    if request.method == "POST":
        if request.POST.get("query"):
            request.session["input_user"] = request.POST.get("query")
            return redirect("off:results")

        # save product
        if request.POST.get("save"):

            product = get_object_or_404(Product, pk=request.POST.get("save"))
            user.product_set.add(product)

    for element in user.product_set.all():
        list_saved_id_products.append(element.id)

    product = get_object_or_404(Product, pk=id_product)

    return render(request, "off/product.html", {
            "product": product,
            "list_saved_id_products": list_saved_id_products,
            "ref_url": ref_url,
    })


@login_required(login_url="login")
def account(request):
    ref_url = 'off:' + request.resolver_match.url_name
    current_user = request.user
    user = get_object_or_404(CustomUser, pk=current_user.id)

    if request.method == 'POST':
        if request.POST.get("query"):
            request.session["input_user"] = request.POST.get("query")
            return redirect("off:results")

    return render(request, "off/account.html", {
            "user": user,
            "ref_url": ref_url,
    })

off/templates/off/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'img/logo_pur_beurre-favicon.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- Custom theme CSS-->
        <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
        <!-- Font family API Open Sans -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />
        <!-- Font Family API Scope+One -->
        <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css" />

    </head>
    <body id="page-top">

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <div>
                    <img src="{% static 'img/logo_pur_beurre.png' %}" alt="logo_pur_beurre" style="width:50px">
                    <a class="navbar-brand js-scroll-trigger ml-4" href="{% url 'off:index' %}">Pur Beurre</a>
                </div>
                {% if user.is_authenticated %}
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        
                        {% if request.get_full_path != '/' %}
                        <li class="nav-item mr-5">
                            <form method="POST" href="{% url ref_url %}">
                            {% csrf_token %}
                                <div class="row justify-content-center align-items-stretch">
                                    <input id="querySearch" type="text" class="control-form mr-1" name="query" placeholder="Rechercher..." style="border-radius:5px; border-color:white; width:300px">
                                    <input id="submitQuery" type="submit" style="display:none">
                                </div>
                            </form>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a id="savedProductsLink" class="nav-link js-scroll-trigger" href="{% url 'off:saved-products' %}">
                                <i class="fas fa-carrot fa-2x"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{% url 'off:account' %}">
                                <i class="fas fa-user fa-2x"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="logoutLink" class="nav-link js-scroll-trigger" href="{% url 'logout' %}">
                                <i class="fas fa-sign-out-alt fa-2x"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                {% else %}
                <div>
                    <a id="signIn" type="button" class="btn btn-outline-primary" href="{% url 'login' %}">Sign In</a>
                    <a id="signUp" type="button" class="btn btn-outline-success" href="{% url 'off:register' %}">Sign Up</a>
                </div>
                {% endif %}
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container">
                <div class="row d-flex flex-row justify-content-around align-tiems-center">
                    <div class="small text-center text-muted">
                        Copyright © 2020 - Pur Beurre</div>
                    <div class="small text-center text-muted">
                        <a href="{% url 'off:legal-notices' %}">Mentions légales</a>
                    </div>
                    <div class="small text-center text-muted">
                        <a href="{% url 'off:contact' %}">Contact</a>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

    </body>
</html>